[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
authors = [
    {email = "hello@futurehouse.org", name = "FutureHouse technical staff"},
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "PyPDF>=3",  # Pin since v1 doesn't work and there's no v2 on PyPI
    "paper-qa",
]
description = "PaperQA readers implemented using PyPDF"
dynamic = ["version"]
license = {file = "LICENSE"}
maintainers = [
    {email = "jamesbraza@gmail.com", name = "James Braza"},
    {email = "michael.skarlinski@gmail.com", name = "Michael Skarlinski"},
    {email = "white.d.andrew@gmail.com", name = "Andrew White"},
]
name = "paper-qa-pypdf"
readme = "README.md"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "fhlmi>=0.39",  # Pin for bytes_to_string
    "paper-qa-pypdf[enhanced,media]",
    "paper-qa>=5.23",  # Pin for PDFParserFn
    "pytest-asyncio",
    "pytest-rerunfailures",
    "pytest>=8",  # Pin to keep recent
]
# Enhanced means: (1) cluster images into figures and (2) parse tables
enhanced = [
    "paper-qa-pypdf[media]",
    "pdfplumber>=0.5",  # Pin for decode_text fixes
]
media = [
    "Pillow",
    "PyPDF[image]",
    "pypdfium2>=4.22.0",  # Pin for PYPDFIUM_INFO addition
]

[tool.ruff]
extend = "../../pyproject.toml"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
root = "../.."
version_file = "src/paperqa_pypdf/version.py"
